### ISSUE TITLE
Ошибка при сборке приложения

### ISSUE THREAD

**Issue by Millon15** [privat-it/cryptonite#12]
Нашёл информацию о данной библиотеке на просторах википедии, спасибо @DJm00n
Склонил, попытался сбилдить по инструкции в `README.md`

Столкнулся со следующей ошибкой:
![image](https://user-images.githubusercontent.com/32433787/71417877-6b808980-2670-11ea-8fd7-01866678e655.png)

**Comment by DJm00n** [comment]
Попробуйте собрать с помощью gradle.
CMake сборка в текущем виде сделана по остаточному принципу.
Или можете попробовать собрать мой форк https://github.com/DJm00n/cryptonite/tree/cmake - я там переписал CMake файлы.

**Comment by outspace** [comment]
Я не уверен что этот Cmake файл предназначался для сборки проекта, больше похоже на Cmake для импорта в IDE. После правок в #13 можно собрать все тесты и примеры.

**Comment by kovalevskij-d** [comment]
Так и есть, cmake добавлен контрибьютором и он не рабочий фактически. Официальная система сборки gradle.
