### ISSUE TITLE
Проблема с pkixUtest

### ISSUE THREAD

**Issue by outspace** [privat-it/cryptonite#2]
Приветствую, 
начну, наверно, с процесса сборки. Собираю я все под 19 студию (windows_x86-64), процессор х64 и система тоже. 
1) gradle ругался что:

> Cannot add task 'help' as a task with that name already exists.

помогло заменить объявление таска с 
`task help()`
на
`task help(overwrite:true)`
я так понял это объявление где-то уже было задефайнено.
2) с флагом компилятора **"/WX"** (который выставлен по умолчанию) тоже не собиралось.

После этих манипуляций вроде собиралось, решил прогнать тесты. Падает на **pkixUtest**:

> 
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_cryptonite_manager.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_cert.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_creq.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_crl.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_ocsp_request.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_ocsp_response.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_sinfo.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_tsp_request.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_tsp_response.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_enveloped_data.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_signed_data.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_ext.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_oids.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_pkix_utils.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_cert_engine.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_crl_engine.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_ocsp_request_engine.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_ocsp_response_engine.c
> C:\git\cryptonite-master\cryptonite-master\src\pkixUtest\c\utest_signed_data_engine.c

Пробовал смотреть дебагером:

> Debug Error!
> 
> Program: ...loads\cryptonite-master\cryptonite-master\Debug\pkixUtest.exe
> 
> HEAP CORRUPTION DETECTED: after Normal block (#1645188) at 0x00000224FB69E570.
> CRT detected that the application wrote to memory after end of heap buffer.
> 

Падает при вызове `esigned_data_free(signed_data_engine)`. Но где конкретно хачится хип сказать не могу.

**Comment by SviatoslavKomkov** [comment]
> Собираю я все под 19 студию (windows_x86-64), процессор х64

Сборка предназначена для vs 2013, по мере свободного времени рассмотрим проблему и добавим сборки для других моделей vs.

> gradle ругался

Какая у вас версия `gradle`? Проверяли на версиях 2.5-4.5.

**Comment by outspace** [comment]
На самом деле, не очень похоже что тут проблемма в версии студии. Изза версий студии может не сликоватся **cryptoniteXtest** но остальное должно работать. 

Использовал последнюю версию gradle (5.6.1)

**Comment by outspace** [comment]
Пробовал под vs 2013, **pkixUtest** проходит, **cryptoniteXtest** падает.

**Comment by outspace** [comment]
Информация для подумать, работал он на 
```
Название ОС:                      Microsoft Windows 7 Максимальная
Версия ОС:                        6.1.7601 Service Pack 1 сборка 7601
```
под ней и собирался. Когда скопировал бинарники собранные (vs 2013) на свою систему (на которой у меня не работало)
```
Название ОС:                      Майкрософт Windows 10 Pro
Версия ОС:                        10.0.18362 Н/Д построение 18362
```
получил итог такой-же как у меня был изначально. Потому делаю вывод что проблема не в версии компилятора.
