### ISSUE TITLE
Проблема с паддингами

### ISSUE THREAD

**Issue by outspace** [privat-it/cryptonite#3]
Заметил что паддинги (PKCS#5 или PKCS#7) добавляются и снимаются не совсем корректно. Проблема в случае когда длинна данных кратна длине блока. В этом случае, в вашей реализации, паддинг не добавляется. 

PKCS#5

>        4. Concatenate M and a padding string PS to form an encoded
>          message EM:
> 
>                  EM = M || PS ,
> 
>          where the padding string PS consists of 8-(||M|| mod 8) octets
>          each with value 8-(||M|| mod 8). The padding string PS will
>          satisfy one of the following statements:
> 
>                  PS = 01, if ||M|| mod 8 = 7 ;
>                  PS = 02 02, if ||M|| mod 8 = 6 ;
>                  ...
>                  PS = 08 08 08 08 08 08 08 08, if ||M|| mod 8 = 0.

PKCS#7

>     2.   Some content-encryption algorithms assume the
>              input length is a multiple of k octets, where k > 1, and
>              let the application define a method for handling inputs
>              whose lengths are not a multiple of k octets. For such
>              algorithms, the method shall be to pad the input at the
>              trailing end with k - (l mod k) octets all having value k -
>              (l mod k), where l is the length of the input. In other
>              words, the input is padded at the trailing end with one of
>              the following strings:
> 
>                       01 -- if l mod k = k-1
>                      02 02 -- if l mod k = k-2
>                                  .
>                                  .
>                                  .
>                    k k ... k k -- if l mod k = 0
> 
>              The padding can be removed unambiguously since all input is
>              padded and no padding string is a suffix of another. This
>              padding method is well-defined if and only if k < 256;
>              methods for larger k are an open issue for further study.

+ не совсем понятно как шифровать большие файлы что бы не загружать их полностью в память?

**Comment by SviatoslavKomkov** [comment]
> Заметил что паддинги (PKCS#5 или PKCS#7) добавляются и снимаются не совсем корректно. Проблема в случае когда длинна данных кратна длине блока. В этом случае, в вашей реализации, паддинг не добавляется.

Спасибо за точное замечание по поводу паддингов. 

Были убраны паддинги из режима cbc и добавлен отдельный код ошибки при передаче данных неправильного размера в режимы ecb и cbc. Теперь размер данных для передачи в режим cbc только кратный размеру блока (по типу openssl).

Для удобства были добавлены функции для работы с паддингами.

**Comment by SviatoslavKomkov** [comment]
> не совсем понятно как шифровать большие файлы что бы не загружать их полностью в память?

Контекст хранит в себе гамму для нужных преобразований. Все что нужно для шифрования больших файлов это вычитывать нужное количество байт и передавать в функцию шифрования\расшифрования.
Пример:
```
int aes_splited_encrypt_test() 
{
    ByteArray *key = ba_alloc_from_le_hex_string("2b7e151628aed2a6abf7158809cf4f3c2b7e151628aed2a6abf7158809cf4f3c");
    ByteArray *iv = ba_alloc_from_le_hex_string("f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff");
    AesCtx *ctx = NULL;
    ByteArray *buffer_ba = NULL;
    ByteArray *encrypted_parts = NULL;
    ByteArray *encrypted_one = NULL;
    ByteArray *data_from_file = NULL;
    ByteArray *data_from_file_padded = NULL;
    ByteArray *padded_buf = NULL;
    ByteArray *encrypted_part = NULL;
    ByteArray *joined = NULL;
    uint8_t buffer[16] = {0};
    FILE *fp = NULL;
    char *filename = "1.txt";
    size_t fsize = 0;
    int ret = RET_OK;
    uint8_t block_size = (uint8_t)ba_get_len(iv);
    bool stop = false;

    fp = fopen(filename,"r");

    if(fp == NULL) {
        printf("Error while opening the file.\n");
        return -1;
    }

    ctx = aes_alloc();
    ret = aes_init_cbc(ctx, key, iv);
    if (ret != RET_OK) {
        goto cleanup;
    }

    encrypted_parts = ba_alloc();

    while(!stop) {
        fsize = fread(buffer, 1, block_size, fp);
        buffer_ba = ba_alloc_from_uint8(buffer, fsize);

        if (fsize % block_size != 0 || fsize == 0) {
            stop = true;
            ret = make_pkcs7_padding(buffer_ba, block_size, &padded_buf);
            if (ret != RET_OK) {
                goto cleanup;
            }
            ba_free(buffer_ba);
            buffer_ba = padded_buf;
            padded_buf = NULL;
        }

        ret = aes_encrypt(ctx, buffer_ba, &encrypted_part);
        if (ret != RET_OK) {
            goto cleanup;
        }

        joined = ba_join(encrypted_parts, encrypted_part);
        ba_free(encrypted_parts);
        ba_free(encrypted_part);
        encrypted_parts = joined;
        joined = NULL;
        encrypted_part = NULL;
    }

    aes_free(ctx);
    ctx = NULL;

    ctx = aes_alloc();
    ret = aes_init_cbc(ctx, key, iv);
    if (ret != RET_OK) {
        goto cleanup;
    }

    ret = ba_alloc_from_file(filename, &data_from_file);
    if (ret != RET_OK) {
        goto cleanup;
    }

    ret = make_pkcs7_padding(data_from_file, block_size, &data_from_file_padded);
    if (ret != RET_OK) {
        goto cleanup;
    }

    ret = aes_encrypt(ctx, data_from_file_padded, &encrypted_one);
    if (ret != RET_OK) {
        goto cleanup;
    }

    if (ba_cmp(encrypted_one, encrypted_parts) == 0) {
        printf("SAME!\n");
    } else {
        printf("NOT SAME!\n");
    }

cleanup:

    ba_free(key);
    ba_free(iv);
    ba_free(buffer_ba);
    ba_free(padded_buf);
    ba_free(encrypted_parts);
    ba_free(encrypted_part);
    ba_free(encrypted_one);
    ba_free(joined);
    ba_free(data_from_file);
    ba_free(data_from_file_padded);
    aes_free(ctx);

    if (fp) {
        fclose(fp);
    }
    if (ret != RET_OK) {
        printf("Error: %d\n", ret);
    }

    return ret;
}
```

**Comment by outspace** [comment]
Спасибо, после разнесения этих функций можно релизовать шифрование частями.
